package de.bdr.asset.management.booking;

/**
 * Booking Status enumeration.
 */
public enum BookingStatusEnum {
    PENDING, // WAITING FOR APPROVAL, ROLE:LINE MANAGER
    APPROVED, // APPROVED BY LINE MANAGER OR ASSET IS BOOKED WITHOUT MANAGER APPROVAL
    CANCELLED, // USER CANCELED IT'S OWN BOOKING
    REJECTED, // ASSET NOT APPROVED BY LINE MANAGER
    COMPLETED // RESERVATION EXPIRED/EXCEEDED
}

// 1.USER BOOKING WITHOUT MANAGER APPROVAL ==== APPROVED / CANCELED / COMPLETED
// 2.USER-BOOKING-WITH-MANAGER-APPROVAL====PENDING->REJECTED/APPROVED/CANCELED(BY-EMPLOYEE)/COMPLETED(AUTO)