spring:
  application:
    name: assetbookingmanagement
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 150
        one-indexed-parameters: true
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        default_schema: asset_booking_mgm
  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: asset_booking_mgm
    default-schema: asset_booking_mgm

feature:
  asset-name-validation-enabled: false

jwt:
  secret: ${JWT_SECRET:1111111111111111111111111111111111111111}
  accessTokenExpiry: ${JWT_EXPIRY_SECONDS:3600}
  refreshTokenExpiry: ${JWT_REFRESH_SECONDS:86400}